### ISSUE TITLE
pip install fails

### ISSUE THREAD

**Issue by JuhoHiltunen** [nordic-institute/X-Road-Security-Server-toolkit#123]
Current installation instructions don't work. Problem with module "cement".

% python3 --version
Python 3.11.5

 % pip3 --version
pip 23.2.1 (python 3.11)

% pip3 install --extra-index-url https://artifactory.niis.org/artifactory/xroad-extensions-release-pypi/ xrdsst --trusted-host artifactory.niis.org

Looking in indexes: https://pypi.org/simple, https://artifactory.niis.org/artifactory/xroad-extensions-release-pypi/
Collecting xrdsst
  Using cached https://artifactory.niis.org/artifactory/xroad-extensions-release-pypi/xrdsst/xrdsst-4.0.0.tar.gz (127 kB)
  Preparing metadata (setup.py): started
  Preparing metadata (setup.py): finished with status 'error'
  error: subprocess-exited-with-error
  
  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [10 lines of output]
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "/private/var/folders/l4/g_505tmn65b6rjvsrq82g9jh0000gp/T/pip-install-f_ptw4nx/xrdsst_92dbdb5d65a5407a9e0ffc3cc113773c/setup.py", line 3, in <module>
          from xrdsst.core.version import get_version
        File "/private/var/folders/l4/g_505tmn65b6rjvsrq82g9jh0000gp/T/pip-install-f_ptw4nx/xrdsst_92dbdb5d65a5407a9e0ffc3cc113773c/xrdsst/__init__.py", line 1, in <module>
          from .core.version import get_version
        File "/private/var/folders/l4/g_505tmn65b6rjvsrq82g9jh0000gp/T/pip-install-f_ptw4nx/xrdsst_92dbdb5d65a5407a9e0ffc3cc113773c/xrdsst/core/version.py", line 2, in <module>
          from cement.utils.version import get_version as cement_get_version
      ModuleNotFoundError: No module named 'cement'
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.

**Comment by JuhoHiltunen** [comment]
Sorry, didn't read prerequisites. Closing.
